const SUBJECT_META = {
  ps:{name:'Probability & Statistics',color:'#e8a23d'}, la:{name:'Linear Algebra',color:'#5aa9e6'},
  co:{name:'Calculus & Optimization',color:'#c792ea'}, pdsa:{name:'Programming, DS & Algorithms',color:'#35d07f'},
  dbms:{name:'Database Mgmt & Warehousing',color:'#ff8a5c'}, ml:{name:'Machine Learning',color:'#ff6b46'},
  ai:{name:'Artificial Intelligence',color:'#f6c445'}, rev:{name:'Full Revision & Mocks',color:'#8a8fa0'}
};
const SUBJECT_ORDER = ['ps','la','co','pdsa','dbms','ml','ai','rev'];

const TOPICS = [
{s:'ps',w:1,t:'Counting: permutations and combinations',f:'nPr = \\dfrac{n!}{(n-r)!},\\quad nCr = \\dfrac{n!}{r!(n-r)!}'},
{s:'ps',w:1,t:'Probability axioms',f:'P(\\Omega)=1,\\ P(A)\\ge 0,\\ P\\left(\\bigcup_i A_i\\right)=\\sum_i P(A_i)'},
{s:'ps',w:1,t:'Sample space',f:'P(A)=\\dfrac{n(A)}{n(\\Omega)}'},
{s:'ps',w:1,t:'Events',f:'P(A^c) = 1-P(A)'},
{s:'ps',w:1,t:'Independent events',f:'P(A\\cap B) = P(A)\\,P(B)'},
{s:'ps',w:1,t:'Mutually exclusive events',f:'P(A\\cap B)=0 \\Rightarrow P(A\\cup B)=P(A)+P(B)'},
{s:'ps',w:1,t:'Marginal probability',f:'P(A) = \\sum_j P(A \\cap B_j)'},
{s:'ps',w:1,t:'Conditional probability',f:'P(A|B) = \\dfrac{P(A\\cap B)}{P(B)}'},
{s:'ps',w:1,t:'Joint probability',f:'P(A\\cap B) = P(A|B)P(B) = P(B|A)P(A)'},
{s:'ps',w:1,t:"Bayes' theorem",f:'P(A_i|B) = \\dfrac{P(B|A_i)P(A_i)}{\\sum_j P(B|A_j)P(A_j)}'},
{s:'ps',w:1,t:'Conditional expectation',f:'E[X|Y{=}y] = \\sum_x x\\,P(X{=}x|Y{=}y)'},
{s:'ps',w:1,t:'Conditional variance',f:'Var(X) = E[Var(X|Y)] + Var(E[X|Y])'},
{s:'ps',w:1,t:'Mean',f:'E[X] = \\sum_x x\\,p(x)\\quad \\text{or}\\quad \\int x f(x)\\,dx'},
{s:'ps',w:2,t:'Median',f:'\\text{value } m:\\ P(X\\le m)\\ge \\tfrac12,\\ P(X\\ge m)\\ge \\tfrac12'},
{s:'ps',w:2,t:'Mode',f:'\\text{value with max } p(x) \\text{ or } f(x)'},
{s:'ps',w:2,t:'Standard deviation',f:'\\sigma = \\sqrt{Var(X)},\\quad Var(X)=E[X^2]-(E[X])^2'},
{s:'ps',w:2,t:'Correlation',f:'\\rho_{XY} = \\dfrac{Cov(X,Y)}{\\sigma_X \\sigma_Y},\\ -1\\le \\rho \\le 1'},
{s:'ps',w:2,t:'Covariance',f:'Cov(X,Y) = E[XY]-E[X]E[Y]'},
{s:'ps',w:2,t:'Random variables',f:'X:\\Omega \\to \\mathbb{R}'},
{s:'ps',w:2,t:'Discrete RVs & probability mass functions',f:'p(x)=P(X{=}x),\\quad \\sum_x p(x)=1'},
{s:'ps',w:2,t:'Uniform distribution (discrete)',f:'p(x)=\\dfrac1n,\\ E[X]=\\dfrac{n+1}{2}'},
{s:'ps',w:2,t:'Bernoulli distribution',f:'P(X{=}1)=p,\\ E[X]=p,\\ Var(X)=p(1-p)'},
{s:'ps',w:2,t:'Binomial distribution',f:'P(X{=}k)=\\binom{n}{k}p^k(1-p)^{n-k},\\ E[X]=np'},
{s:'ps',w:2,t:'Continuous RVs & probability distribution function',f:'P(a\\le X\\le b)=\\int_a^b f(x)\\,dx,\\ \\int f(x)\\,dx=1'},
{s:'ps',w:2,t:'Uniform distribution (continuous)',f:'f(x)=\\dfrac{1}{b-a},\\ E[X]=\\dfrac{a+b}{2}'},
{s:'ps',w:3,t:'Exponential distribution',f:'f(x)=\\lambda e^{-\\lambda x},\\ E[X]=\\dfrac1\\lambda'},
{s:'ps',w:3,t:'Poisson distribution',f:'P(X{=}k)=\\dfrac{e^{-\\lambda}\\lambda^k}{k!},\\ E[X]=Var(X)=\\lambda'},
{s:'ps',w:3,t:'Normal distribution',f:'f(x)=\\dfrac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}'},
{s:'ps',w:3,t:'Standard normal distribution',f:'Z=\\dfrac{X-\\mu}{\\sigma}\\sim N(0,1)'},
{s:'ps',w:3,t:'t-distribution',f:'T=\\dfrac{Z}{\\sqrt{\\chi^2_\\nu/\\nu}}'},
{s:'ps',w:3,t:'Chi-squared distribution',f:'\\chi^2=\\sum_{i=1}^{\\nu} Z_i^2'},
{s:'ps',w:3,t:'Cumulative distribution function (CDF)',f:'F(x)=P(X\\le x)=\\int_{-\\infty}^{x} f(t)\\,dt'},
{s:'ps',w:3,t:'Conditional PDF',f:'f(x|y)=\\dfrac{f(x,y)}{f_Y(y)}'},
{s:'ps',w:3,t:'Central limit theorem',f:'\\dfrac{\\bar X-\\mu}{\\sigma/\\sqrt n}\\ \\xrightarrow{d}\\ N(0,1)'},
{s:'ps',w:3,t:'Confidence interval',f:'\\bar X \\pm z_{\\alpha/2}\\dfrac{\\sigma}{\\sqrt n}'},
{s:'ps',w:3,t:'z-test',f:'z=\\dfrac{\\bar X-\\mu_0}{\\sigma/\\sqrt n}'},
{s:'ps',w:3,t:'t-test',f:'t=\\dfrac{\\bar X-\\mu_0}{s/\\sqrt n},\\ df=n-1'},
{s:'ps',w:3,t:'Chi-squared test',f:'\\chi^2=\\sum \\dfrac{(O_i-E_i)^2}{E_i}'},
{s:'la',w:4,t:'Vector space',tip:'A set closed under vector addition and scalar multiplication'},
{s:'la',w:4,t:'Subspaces',f:'W\\subseteq V:\\ 0\\in W,\\ \\text{closed under }+,\\cdot'},
{s:'la',w:4,t:'Linear dependence and independence of vectors',f:'c_1v_1+\\dots+c_nv_n=0 \\Rightarrow \\text{all }c_i=0'},
{s:'la',w:4,t:'Matrices: fundamentals',f:'(AB)^T=B^TA^T,\\quad (AB)^{-1}=B^{-1}A^{-1}'},
{s:'la',w:4,t:'Projection matrix',f:'P=A(A^TA)^{-1}A^T,\\quad P^2=P=P^T'},
{s:'la',w:4,t:'Orthogonal matrix',f:'Q^TQ=I,\\quad Q^{-1}=Q^T,\\quad \\det(Q)=\\pm1'},
{s:'la',w:4,t:'Idempotent matrix',f:'A^2=A'},
{s:'la',w:4,t:'Partition matrix and its properties',tip:'Block matrices multiply block-by-block'},
{s:'la',w:4,t:'Quadratic forms',f:'Q(x)=x^TAx;\\ \\text{PD if } x^TAx>0'},
{s:'la',w:5,t:'Systems of linear equations and their solutions',f:'Ax=b \\text{ consistent} \\iff rank(A)=rank([A|b])'},
{s:'la',w:5,t:'Gaussian elimination',tip:'Row-reduce [A|b] to echelon form'},
{s:'la',w:5,t:'Eigenvalues and eigenvectors',f:'Av=\\lambda v \\iff \\det(A-\\lambda I)=0'},
{s:'la',w:5,t:'Determinant',f:'\\det(AB)=\\det(A)\\det(B)'},
{s:'la',w:5,t:'Rank',f:'rank(A)=\\dim(\\text{column space of }A)'},
{s:'la',w:5,t:'Nullity',f:'rank(A)+nullity(A)=n'},
{s:'la',w:5,t:'Projections',f:'\\text{proj}_u(v)=\\dfrac{u\\cdot v}{u\\cdot u}\\,u'},
{s:'la',w:5,t:'LU decomposition',f:'A=LU\\ \\text{(}L\\text{ lower, }U\\text{ upper)}'},
{s:'la',w:5,t:'Singular value decomposition (SVD)',f:'A=U\\Sigma V^T'},
{s:'co',w:6,t:'Functions of a single variable',f:'f:\\mathbb R \\to \\mathbb R'},
{s:'co',w:6,t:'Limits',f:'\\lim_{x \\to a} f(x) = L \\iff \\forall \\epsilon >0, \\exists \\delta >0: |x-a| <\\delta \\Rightarrow |f(x)-L) <\\epsilon)'.replace(')','')},
{s:'co',w:6,t:'Continuity',f:'f \\text{ continuous at } a \\iff \\lim_{x\\to a} f(x)=f(a)'},
{s:'co',w:6,t:'Differentiability',f:"f'(a)=\\lim_{h\\to 0}\\dfrac{f(a+h)-f(a)}{h}"},
{s:'co',w:6,t:'Chain rule',f:"(f \\circ g)'(x) = f'(g(x))\\cdot g'(x)"},
{s:'co',w:6,t:'Product rule',f:"(fg)'(x)=f'(x)g(x)+f(x)g'(x)"},
{s:'co',w:6,t:'Quotient rule',f:"\\left(\\dfrac{f}{g}\\right)'(x)=\\dfrac{f'(x)g(x)-f(x)g'(x)}{(g(x))^2}"},
{s:'co',w:6,t:'Critical points and extrema',f:"f'(a)=0 \\text{ or undefined}"},
{s:'co',w:7,t:'Concavity and inflection points',f:"f''(x) >0 \\text{ (convex)}, \\quad f''(x) <0 \\text{ (concave)}"},
{s:'co',w:7,t:'Integration (Riemann)',f:'\\int_a^b f(x)\\,dx = \\lim_{n\\to\\infty}\\sum_{i=1}^{n} f(x_i^*)\\Delta x'},
{s:'co',w:7,t:'Fundamental theorem of calculus',f:'\\dfrac{d}{dx}\\int_a^x f(t)\\,dt = f(x)'},
{s:'co',w:7,t:'Integration by parts',f:'\\int u\\,dv = uv - \\int v\\,du'},
{s:'co',w:7,t:'Substitution rule',f:"\\int f(g(x))g'(x)\\,dx = \\int f(u)\\,du"},
{s:'co',w:7,t:'Partial derivatives',f:'\\dfrac{\\partial f}{\\partial x_i} = \\lim_{h\\to 0} \\dfrac{f(x_1,\\dots,x_i+h,\\dots,x_n)-f(x)}{h}'},
{s:'co',w:7,t:'Gradient',f:'\\nabla f = \\left(\\dfrac{\\partial f}{\\partial x_1}, \\ldots, \\dfrac{\\partial f}{\\partial x_n}\\right)'},
{s:'co',w:7,t:'Hessian matrix',f:'H = \\begin{pmatrix} \\frac{\\partial^2 f}{\\partial x_1^2} & \\cdots & \\frac{\\partial^2 f}{\\partial x_1 \\partial x_n} \\\\ \\vdots & \\ddots & \\vdots \\\\ \\frac{\\partial^2 f}{\\partial x_n \\partial x_1} & \\cdots & \\frac{\\partial^2 f}{\\partial x_n^2} \\end{pmatrix}'},
{s:'co',w:8,t:'Convexity and convex functions',f:'f(\\lambda x + (1-\\lambda)y) \\le \\lambda f(x) + (1-\\lambda)f(y)'},
{s:'co',w:8,t:'Lagrange multipliers',f:'\\nabla f = \\lambda \\nabla g \\text{ at constrained optimum}'},
{s:'co',w:8,t:'KKT conditions',f:'\\nabla f(x^*) + \\sum_i \\lambda_i \\nabla g_i(x^*) + \\sum_j \\mu_j \\nabla h_j(x^*) = 0'},
{s:'co',w:8,t:'Gradient descent',f:'x_{t+1} = x_t - \\alpha \\nabla f(x_t)'},
{s:'co',w:8,t:"Newton's method",f:'x_{t+1} = x_t - [H(x_t)]^{-1}\\nabla f(x_t)'},
{s:'pdsa',w:9,t:'Arrays and linked lists',tip:'Basic sequential data structures'},
{s:'pdsa',w:9,t:'Stacks and queues',tip:'LIFO and FIFO data structures'},
{s:'pdsa',w:9,t:'Trees and binary trees',tip:'Hierarchical data structures'},
{s:'pdsa',w:9,t:'Graphs and graph traversal',tip:'BFS, DFS, topological sort'},
{s:'pdsa',w:9,t:'Sorting algorithms',f:'\\text{Quicksort, Mergesort, Heapsort } O(n \\log n)'},
{s:'pdsa',w:9,t:'Binary search',f:'\\log_2 n \\text{ time complexity on sorted arrays}'},
{s:'pdsa',w:10,t:'Hash tables',tip:'Average O(1) insertion, deletion, search'},
{s:'pdsa',w:10,t:'Asymptotic analysis: Big O, Theta, Omega',f:'O(f(n)), \\Theta(f(n)), \\Omega(f(n))'},
{s:'pdsa',w:10,t:'Dynamic programming',tip:'Optimal substructure and overlapping subproblems'},
{s:'pdsa',w:10,t:'Greedy algorithms',tip:'Make locally optimal choices'},
{s:'dbms',w:11,t:'Relational data model',tip:'Tables, rows, columns, keys'},
{s:'dbms',w:11,t:'SQL: SELECT, WHERE, JOIN',tip:'Fundamental query operations'},
{s:'dbms',w:11,t:'Normalization: 1NF, 2NF, 3NF',tip:'Eliminating redundancy'},
{s:'dbms',w:11,t:'Transactions and ACID properties',f:'\\text{Atomicity, Consistency, Isolation, Durability}'},
{s:'dbms',w:11,t:'Indexing',tip:'B-tree and hash indices'},
{s:'dbms',w:11,t:'Query optimization',tip:'Cost models and execution plans'},
{s:'dbms',w:12,t:'Measures: computations',tip:'Aggregate functions: SUM, COUNT, AVG, MIN, MAX'},
{s:'ml',w:9,t:'Regression and classification problems',f:'y=f(x)+\\epsilon\\ \\text{(regression)};\\quad y\\in\\{1,\\dots,K\\}\\ \\text{(classification)}'},
{s:'ml',w:9,t:'Simple linear regression',f:'\\hat\\beta_1=\\dfrac{Cov(X,Y)}{Var(X)},\\quad \\hat\\beta_0=\\bar y-\\hat\\beta_1\\bar x'},
{s:'ml',w:9,t:'Multiple linear regression',f:'\\hat\\beta=(X^TX)^{-1}X^Ty'},
{s:'ml',w:9,t:'Ridge regression',f:'\\hat\\beta=(X^TX+\\lambda I)^{-1}X^Ty'},
{s:'ml',w:9,t:'Logistic regression',f:'p=\\dfrac{1}{1+e^{-(\\beta_0+\\beta_1 x)}}'},
{s:'ml',w:9,t:'k-nearest neighbour',tip:'Classify by majority vote among the k nearest points'},
{s:'ml',w:9,t:'Naive Bayes classifier',f:'P(y|x)\\propto P(y)\\prod_i P(x_i|y)'},
{s:'ml',w:9,t:'Linear discriminant analysis',f:'\\max \\dfrac{(\\mu_1-\\mu_2)^2}{\\sigma_1^2+\\sigma_2^2}'},
{s:'ml',w:9,t:'Support vector machine',f:'\\max \\dfrac{2}{\\|w\\|}\\quad \\text{s.t. } y_i(w\\cdot x_i+b)\\ge1'},
{s:'ml',w:9,t:'Decision trees',tip:'Split on the feature giving maximum information gain'},
{s:'ml',w:9,t:'Bias-variance trade-off',f:'E[(y-\\hat y)^2] = Bias^2+Variance+\\sigma^2'},
{s:'ml',w:10,t:'Leave-one-out (LOO) cross-validation',f:'n \\text{ folds — train on } n{-}1,\\ \\text{test on the } 1'},
{s:'ml',w:10,t:'k-fold cross-validation',f:'k \\text{ folds — train on } k{-}1,\\ \\text{test on the remaining fold}'},
{s:'ml',w:10,t:'Multi-layer perceptron',f:'a^{(l)}=\\sigma\\!\\left(W^{(l)}a^{(l-1)}+b^{(l)}\\right)'},
{s:'ml',w:10,t:'Feed-forward neural network',f:'\\hat y = \\sigma(W_2\\,\\sigma(W_1x+b_1)+b_2)'},
{s:'ml',w:10,t:'Clustering algorithms (overview)',tip:'Group unlabelled data by similarity'},
{s:'ml',w:10,t:'k-means clustering',f:'\\min \\sum_k\\sum_{x\\in C_k}\\|x-\\mu_k\\|^2'},
{s:'ml',w:10,t:'k-medoid clustering',tip:'Like k-means, but each cluster centre is an actual data point'},
{s:'ml',w:10,t:'Hierarchical clustering: divisive (top-down)',tip:'Start with one cluster and recursively split it'},
{s:'ml',w:10,t:'Hierarchical clustering: agglomerative, single-linkage',f:'d(A,B)=\\min_{a\\in A,\\,b\\in B}\\|a-b\\|'},
{s:'ml',w:10,t:'Hierarchical clustering: complete/multiple-linkage',f:'d(A,B)=\\max_{a\\in A,\\,b\\in B}\\|a-b\\|'},
{s:'ml',w:10,t:'Dimensionality reduction',tip:'Reduce feature count while preserving information'},
{s:'ml',w:10,t:'Principal component analysis (PCA)',tip:'Eigenvectors of the covariance matrix, sorted by eigenvalue'},
{s:'ai',w:11,t:'Search: uninformed',tip:'BFS, DFS, uniform-cost search — no heuristic used'},
{s:'ai',w:11,t:'Search: informed',f:'f(n)=g(n)+h(n)\\ \\text{(A* search)}'},
{s:'ai',w:11,t:'Search: adversarial',tip:'Minimax search, with alpha-beta pruning'},
{s:'ai',w:11,t:'Logic: propositional',f:'\\wedge,\\ \\vee,\\ \\neg,\\ \\rightarrow,\\ \\leftrightarrow'},
{s:'ai',w:11,t:'Logic: predicate',f:'\\forall x\\,P(x),\\quad \\exists x\\,P(x)'},
{s:'ai',w:11,t:'Reasoning under uncertainty: conditional independence',f:'P(X,Y|Z)=P(X|Z)\\,P(Y|Z)'},
{s:'ai',w:11,t:'Exact inference: variable elimination',tip:'Sum out variables one at a time via factor marginalization'},
{s:'ai',w:11,t:'Approximate inference: sampling',tip:'Monte Carlo methods — likelihood weighting, Gibbs sampling'},
{s:'rev',w:12,t:'Full revision — Probability, Linear Algebra, Calculus',tip:'Redo your formula sheet; work 10 mixed problems per topic'},
{s:'rev',w:12,t:'Full revision — PDSA, DBMS, ML, AI',tip:'Redo your formula sheet; work 10 mixed problems per topic'},
{s:'rev',w:12,t:'Previous year GATE DA paper — attempt 1',tip:'Simulate full 3-hour test conditions, no notes'},
{s:'rev',w:12,t:'Previous year GATE DA paper — attempt 2',tip:'Simulate full 3-hour test conditions, no notes'},
{s:'rev',w:12,t:'Full-length mock test 1',tip:'Analyze section-wise accuracy and timing right after'},
{s:'rev',w:12,t:'Full-length mock test 2',tip:'Analyze section-wise accuracy and timing right after'},
{s:'rev',w:12,t:'Rework mistakes from mocks & weak topics',tip:'Keep a running error log — revisit it the night before the exam'},
{s:'rev',w:12,t:'Final formula & concept sheet pass',tip:'One page per subject — glance through on exam morning only'}
];
function _stableTopicId(s,t){let h=0;const str=s+'|'+t;for(let i=0;i<str.length;i++)h=Math.imul(31,h)+str.charCodeAt(i)|0;return 't'+Math.abs(h).toString(36)}
TOPICS.forEach(t=>t.id=_stableTopicId(t.s,t.t));

const MATH_DATABASE = {
"counting: permutations and combinations":{def:"Combinatorics of constraints, partitions and allocations over discrete sets.",thm:"<h5>Stars and Bars</h5><p>Non-negative solutions of $\\sum_{i=1}^k x_i=n$: $\\binom{n+k-1}{k-1}$; positive: $\\binom{n-1}{k-1}$.</p>",ctr:"<span class=\"counter-title\">Distinct vs Indistinct</span>Stirling numbers (distinct→indistinct buckets) are not combinations.",ex:"<p><strong>Problem:</strong> 5 distinct queues get 12 identical packets; P(no queue empty)?</p><p><strong>Solution:</strong> $\\binom{16}{4}=1820$ total, $\\binom{11}{4}=330$ positive → $33/182$.</p>"},
"probability axioms":{def:"Kolmogorov postulates: non-negativity, normalisation, countable additivity for disjoint events.",thm:"<h5>Union Bound</h5><p>$P(\\bigcup_i A_i)\\le\\sum_i P(A_i)$; equality iff disjoint.</p>",ctr:"<span class=\"counter-title\">Overlap Error</span>$P(A\\cup B)\\ne P(A)+P(B)$ unless $A\\cap B=\\emptyset$.",ex:"<p><strong>Problem:</strong> P(A)=.95, P(B)=.92, P(A∩B)=.88. Fails ≥1?</p><p><strong>Solution:</strong> $1-0.88=0.12$.</p>"},
"conditional probability":{def:"$P(A|B)$: probability of A in the restricted space where B occurred.",thm:"<h5>Chain Rule</h5><p>$P(A_1\\cap\\cdots\\cap A_n)=P(A_1)P(A_2|A_1)\\cdots P(A_n|A_1\\cap\\cdots\\cap A_{n-1})$.</p>",ctr:"<span class=\"counter-title\">Inversion Fallacy</span>$P(A|B)\\ne P(B|A)$ without Bayes.",ex:"<p><strong>Problem:</strong> 99% sens, 98% spec, 0.1% prev; P(disease|+)?</p><p><strong>Solution:</strong> $P(T)=0.02097$ → $0.00099/0.02097\\approx4.72\\%$.</p>"},
"bayes' theorem":{def:"Belief update from prior + likelihood to posterior.",thm:"<h5>Partition Form</h5><p>$P(B_i|A)=\\frac{P(A|B_i)P(B_i)}{\\sum_j P(A|B_j)P(B_j)}$.</p>",ctr:"<span class=\"counter-title\">Prior Neglect</span>Ignoring $P(B_i)$ biases every update.",ex:"<p><strong>Problem:</strong> Urns 3R2B/2R3B/1R4B, uniform urn, red drawn → P(Urn1)?</p><p><strong>Solution:</strong> $P(R)=2/5$; posterior $=1/2$.</p>"},
"poisson distribution":{def:"Binomial limit ($n\\to\\infty,p\\to0,np=\\lambda$) for rare events per interval.",thm:"<h5>Additivity</h5><p>$\\text{Poi}(\\lambda_1)+\\text{Poi}(\\lambda_2)=\\text{Poi}(\\lambda_1+\\lambda_2)$ if independent.</p>",ctr:"<span class=\"counter-title\">Clumping</span>Temporal clustering violates independent increments.",ex:"<p><strong>Problem:</strong> 3 faults/hr; P(2 in first 20min | 5 in hour)?</p><p><strong>Solution:</strong> $X\\sim Poi(1),Y\\sim Poi(2)$: $\\frac{P(X=2)P(Y=3)}{P(X+Y=5)}=80/243$.</p>"},
"normal distribution":{def:"Bell curve $N(\\mu,\\sigma^2)$.",thm:"<h5>CLT</h5><p>$\\frac{\\bar X_n-\\mu}{\\sigma/\\sqrt n}\\xrightarrow{d}N(0,1)$.</p>",ctr:"<span class=\"counter-title\">Unverified Normality</span>Check Q-Q / Shapiro-Wilk first.",ex:"<p><strong>Problem:</strong> $N(500,100^2)$; P(400≤X≤650)?</p><p><strong>Solution:</strong> $\\Phi(1.5)-\\Phi(-1)\\approx0.7745$.</p>"},
"vector space":{def:"Set closed under addition and scalar multiplication satisfying the axioms.",thm:"<h5>Basis/Dimension</h5><p>All bases have equal cardinality = dimension.</p>",ctr:"<span class=\"counter-title\">Span ≠ Independence</span>Dependent sets can span; independent sets may span less.",ex:"<p><strong>Problem:</strong> Basis of $\\mathbb R^3$: [1,0,1],[0,1,1],[1,1,2]?</p><p><strong>Solution:</strong> $v_3=v_1+v_2$ → rank 2 → no.</p>"},
"eigenvalues and eigenvectors":{def:"$Av=\\lambda v$, $v\\ne0$.",thm:"<h5>Spectral Theorem</h5><p>Symmetric $A=QDQ^T$ with orthonormal eigenvectors.</p>",ctr:"<span class=\"counter-title\">Defective Matrices</span>Not all matrices diagonalize (Jordan form).",ex:"<p><strong>Problem:</strong> Eigen-pairs of [[3,1],[1,3]]?</p><p><strong>Solution:</strong> $\\lambda=2,4$; $v=[1,-1]^T,[1,1]^T$.</p>"},
"singular value decomposition (svd)":{def:"$A=U\\Sigma V^T$ for any real matrix.",thm:"<h5>Eckart–Young</h5><p>Best rank-k approx keeps top-k singular values.</p>",ctr:"<span class=\"counter-title\">σ ≠ λ</span>$\\sigma_i=\\sqrt{\\lambda_i(A^TA)}\\ge0$.",ex:"<p><strong>Problem:</strong> SVD of diag(3,−2)?</p><p><strong>Solution:</strong> $\\sigma=(3,2)$, $U=diag(1,-1)$, $V=I$.</p>"},
"projection matrix":{def:"Orthogonal projector onto a column space.",thm:"<h5>Idempotency</h5><p>$P^2=P=P^T$, $\\lambda\\in\\{0,1\\}$.</p>",ctr:"<span class=\"counter-title\">Wrong Formula</span>$AA^T$ is not a projector unless columns orthonormal.",ex:"<p><strong>Problem:</strong> Projector onto span{[1,1,0],[0,1,1]}?</p><p><strong>Solution:</strong> $P=\\frac13\\begin{pmatrix}2&1&-1\\\\1&2&1\\\\-1&1&2\\end{pmatrix}$.</p>"},
"limits":{def:"ε–δ definition of $\\lim_{x\\to a}f(x)=L$.",thm:"<h5>Limit Laws</h5><p>Sum/product/quotient (denominator ≠ 0) of limits.</p>",ctr:"<span class=\"counter-title\">One-sided Mismatch</span>Two-sided limit needs both sides equal.",ex:"<p><strong>Problem:</strong> $\\lim_{x\\to2}\\frac{x^2-4}{x-2}$?</p><p><strong>Solution:</strong> $=4$.</p>"},
"continuity":{def:"$\\lim_{x\\to a}f(x)=f(a)$.",thm:"<h5>IVT</h5><p>Continuous on [a,b] attains every intermediate value.</p>",ctr:"<span class=\"counter-title\">Dirichlet Function</span>1 on ℚ else 0 — nowhere continuous.",ex:"<p><strong>Problem:</strong> $\\alpha(T)=\\frac{\\sqrt{T^2+16}-4}{T^2}$, $\\alpha(0)=k$; find k.</p><p><strong>Solution:</strong> $k=1/8$.</p>"},
"chain rule":{def:"$\\frac{dy}{dx}=\\frac{dy}{du}\\frac{du}{dx}$.",thm:"<h5>Jacobian Form</h5><p>$D(f\\circ g)=Df\\cdot Dg$.</p>",ctr:"<span class=\"counter-title\">Inner Derivative</span>$\\frac{d}{dx}\\sin(x^2)=2x\\cos(x^2)$.",ex:"<p><strong>Problem:</strong> $\\frac{d}{dx}e^{-x^2}$?</p><p><strong>Solution:</strong> $-2xe^{-x^2}$.</p>"},
"gradient descent":{def:"$x_{t+1}=x_t-\\alpha\\nabla f(x_t)$.",thm:"<h5>Linear Rate</h5><p>Strongly convex + Lipschitz gradient → geometric convergence.</p>",ctr:"<span class=\"counter-title\">Fixed Step</span>Ill-scaled gradients oscillate/stagnate with constant α.",ex:"<p><strong>Problem:</strong> $f=x^2+4y^2$ from (2,1), α=0.1, two steps?</p><p><strong>Solution:</strong> (1.6,0.2) → (1.28,0.04).</p>"},
"convexity and convex functions":{def:"Chord lies above graph.",thm:"<h5>Second-order</h5><p>Convex ⇔ Hessian  0 everywhere.</p>",ctr:"<span class=\"counter-title\">Convex vs Concave</span>Maximizing convex / minimizing concave is hard.",ex:"<p><strong>Problem:</strong> Is $x^2+xy+y^2$ convex?</p><p><strong>Solution:</strong> Hessian eigenvalues 1,3 > 0 → yes.</p>"},
"regression and classification problems":{def:"Continuous output vs discrete label prediction.",thm:"<h5>Bias-Variance</h5><p>$E[(y-\\hat y)^2]=Bias^2+Var+\\sigma^2$.</p>",ctr:"<span class=\"counter-title\">Imbalance</span>Accuracy misleads; use F1/AUC-ROC.",ex:"<p><strong>Problem:</strong> 95/5 classes; all-zero classifier 95% acc — why bad?</p><p><strong>Solution:</strong> Recall₁=0, F1=0.</p>"},
"logistic regression":{def:"Log-odds linear in features; $p=\\sigma(\\beta_0+\\beta_1x)$.",thm:"<h5>MLE</h5><p>Cross-entropy log-likelihood maximized by gradient ascent.</p>",ctr:"<span class=\"counter-title\">OLS on Binary</span>Predictions can leave [0,1].",ex:"<p><strong>Problem:</strong> log-odds $=-2+0.5x$; p at x=4?</p><p><strong>Solution:</strong> 0.5.</p>"},
"support vector machine":{def:"Max-margin classifier; $\\min\\frac12\\|w\\|^2$ s.t. $y_i(w\\cdot x_i+b)\\ge1$.",thm:"<h5>Kernel Trick</h5><p>Inner products in feature space without explicit mapping.</p>",ctr:"<span class=\"counter-title\">Scaling</span>SVM margins are scale-sensitive.",ex:"<p><strong>Problem:</strong> Separator for (1,1),(2,2) vs (1,2),(2,1)?</p><p><strong>Solution:</strong> $x_1+x_2=2.5$, margin $1/\\sqrt2$.</p>"},
"k-means clustering":{def:"Minimize within-cluster squared distances.",thm:"<h5>Convergence</h5><p>Objective monotonically decreases → local min in finite steps.</p>",ctr:"<span class=\"counter-title\">Initialization</span>Use k-means++ / restarts.",ex:"<p><strong>Problem:</strong> Cluster {[0,0],[0,2],[3,3],[3,5]}, k=2, μ=(0,0),(3,3)?</p><p><strong>Solution:</strong> Converges to {0,0;0,2} & {3,3;3,5}.</p>"},
"principal component analysis (pca)":{def:"Top eigenvectors of covariance = max-variance directions.",thm:"<h5>Optimal Reconstruction</h5><p>First k PCs minimize squared projection error.</p>",ctr:"<span class=\"counter-title\">Unscaled Features</span>Standardize first.",ex:"<p><strong>Problem:</strong> First PC of Σ=[[4,1],[1,2]]?</p><p><strong>Solution:</strong> $\\lambda_1=3+\\sqrt2$, $v_1\\propto[1,\\sqrt2-1]^T$.</p>"}
};

/* ===== game banks ===== */
const FLASH=[
{s:0,q:"State Bayes' theorem.",a:"P(A|B) = P(B|A)·P(A) / P(B)"},
{s:0,q:"Variance of Binomial(n, p)?",a:"np(1−p)"},
{s:0,q:"What does the CLT say?",a:"For large n, X̄ ≈ N(μ, σ²/n) regardless of population shape."},
{s:0,q:"z critical value for a 95% CI?",a:"≈ 1.96"},
{s:1,q:"When is A invertible?",a:"det(A) ≠ 0 ⇔ full rank ⇔ no zero eigenvalue."},
{s:1,q:"Rank–nullity theorem?",a:"rank(A) + nullity(A) = number of columns."},
{s:1,q:"Projection matrix property?",a:"P² = P = Pᵀ."},
{s:2,q:"Definition of the derivative?",a:"f′(x) = lim h→0 [f(x+h) − f(x)] / h"},
{s:2,q:"Second derivative test?",a:"f′=0, f″<0 → max; f″>0 → min."},
{s:3,q:"Best case of insertion sort?",a:"O(n) — already sorted."},
{s:3,q:"Dijkstra's catch?",a:"Non-negative edge weights only."},
{s:4,q:"Why normalize?",a:"Kill redundancy + update anomalies (1NF → BCNF)."},
{s:4,q:"Star vs snowflake schema?",a:"Star: denormalized dims; snowflake: normalized dims."},
{s:5,q:"L1 vs L2 regularisation?",a:"L1 → sparsity; L2 → shrinkage."},
{s:5,q:"The sigmoid?",a:"σ(z) = 1/(1+e⁻ᶻ)."},
{s:5,q:"PCA explained variance?",a:"λᵢ / Σλⱼ."},
{s:6,q:"Admissible heuristic?",a:"Never overestimates: h(n) ≤ h*(n)."},
{s:6,q:"Modus ponens?",a:"From A and A⇒B, infer B."}
];
const MCQS=[
{s:0,q:"If A and B are mutually exclusive, P(A∪B) = ?",o:["P(A)·P(B)","P(A)+P(B)","P(A)−P(B)","1−P(A)P(B)"],a:1},
{s:0,q:"For X ~ Binomial(n, p), E[X] = ?",o:["np(1−p)","n+p","np","p/n"],a:2},
{s:0,q:"Which test checks independence of two categorical variables?",o:["z-test","t-test","Chi-squared test","Paired t-test"],a:2},
{s:0,q:"By the CLT, the sampling distribution of the mean (large n) ≈ ?",o:["Uniform","Binomial","Exponential","Normal"],a:3},
{s:0,q:"Bayes' theorem: P(A|B) = ?",o:["P(B|A)·P(A) / P(B)","P(A|B)·P(B) / P(A)","P(A∩B) / P(A)","P(A)+P(B)"],a:0},
{s:0,q:"Var(X) equals …",o:["E[X²] − (E[X])²","(E[X])² − E[X²]","E[X²] + (E[X])²","E[X]²"],a:0},
{s:1,q:"For an m×n matrix A, rank(A) + nullity(A) = ?",o:["m","n","m+n","m−n"],a:1},
{s:1,q:"If A² = A, then A is …",o:["orthogonal","nilpotent","idempotent","singular"],a:2},
{s:1,q:"The sum of eigenvalues of A equals its …",o:["determinant","trace","rank","norm"],a:1},
{s:1,q:"The SVD factorizes A as …",o:["LU","QR","PDP⁻¹","UΣVᵀ"],a:3},
{s:1,q:"det [[a, b], [c, d]] = ?",o:["ad − bc","ab − cd","ac − bd","ad + bc"],a:0},
{s:2,q:"lim(x→0) sin(x)/x = ?",o:["0","1","∞","Does not exist"],a:1},
{s:2,q:"At an interior extremum of a differentiable f, …",o:["f′(x) = 0","f″(x) = 0","f(x) = 0","f′(x) > 0"],a:0},
{s:2,q:"Taylor series of eˣ about 0 is …",o:["Σ xⁿ","Σ xⁿ/n!","Σ n·xⁿ","1 − x²/2 only"],a:1},
{s:3,q:"Binary search requires …",o:["a sorted array","a linked list","a hash table","O(n) extra space"],a:0},
{s:3,q:"Worst-case time complexity of mergesort is …",o:["O(n²)","O(n log n)","O(log n)","O(n)"],a:1},
{s:3,q:"BFS is naturally implemented with a …",o:["stack","heap","queue","priority queue"],a:2},
{s:3,q:"Average-case lookup in a hash table is …",o:["O(n)","O(log n)","O(n log n)","O(1)"],a:3},
{s:4,q:"In relational algebra, σ (sigma) denotes …",o:["project","select","join","union"],a:1},
{s:4,q:"First normal form (1NF) requires …",o:["no transitive dependencies","atomic attribute values","no partial dependencies","a BCNF schema"],a:1},
{s:4,q:"In BCNF, every determinant must be …",o:["a candidate key","a foreign key","numeric","unique-valued only"],a:0},
{s:5,q:"Ridge regression uses which penalty?",o:["L1 norm","L∞ norm","L2 norm","No penalty"],a:2},
{s:5,q:"Leave-one-out CV on n samples uses how many folds?",o:["2","10","√n","n"],a:3},
{s:5,q:"The first principal component maximizes …",o:["class separation","variance of projections","distance to origin","entropy"],a:1},
{s:5,q:"Entropy of a PURE node is …",o:["1","0","0.5","∞"],a:1},
{s:6,q:"A* search is optimal when the heuristic is …",o:["random","admissible","overestimating","constant"],a:1},
{s:6,q:"Minimax search is used for …",o:["single-agent pathfinding","adversarial games","sorting","clustering"],a:1},
{s:6,q:"Which of these is an UNINFORMED search?",o:["A*","Greedy best-first","BFS","Hill climbing"],a:2}
];
const NATS=[
{s:0,q:"P(A)=0.4, P(B)=0.5, A and B independent. P(A∩B)?",a:0.2},
{s:0,q:"X ~ Binomial(8, 0.5). E[X]?",a:4},
{s:1,q:"Determinant of [[3, 2], [1, 4]]?",a:10},
{s:1,q:"A is 4×6 with rank 4. Nullity of A?",a:2},
{s:2,q:"f(x) = x² − 6x + 10. Minimum value of f?",a:1},
{s:2,q:"d/dx(x³) evaluated at x = 2?",a:12},
{s:3,q:"Binary search on 1024 sorted elements: max comparisons ≈ log₂(1024) = ?",a:10},
{s:5,q:"Entropy of a fair coin flip, in bits?",a:1},
{s:6,q:"A*: g(n)=5, h(n)=3. f(n)?",a:8}
];
const FORMULAS=[
{s:'ps',t:'Permutations',f:'P(n,r)=\\dfrac{n!}{(n-r)!}'},{s:'ps',t:'Combinations',f:'C(n,r)=\\dfrac{n!}{r!(n-r)!}'},
{s:'ps',t:'Addition rule',f:'P(A\\cup B)=P(A)+P(B)-P(A\\cap B)'},{s:'ps',t:'Conditional probability',f:'P(A|B)=\\dfrac{P(A\\cap B)}{P(B)}'},
{s:'ps',t:'Independence',f:'P(A\\cap B)=P(A)\\,P(B)'},{s:'ps',t:"Bayes' theorem",f:'P(A_i|B)=\\dfrac{P(B|A_i)P(A_i)}{\\sum_j P(B|A_j)P(A_j)}'},
{s:'ps',t:'Variance',f:'Var(X)=E[X^2]-(E[X])^2'},{s:'ps',t:'Covariance',f:'Cov(X,Y)=E[XY]-E[X]E[Y]'},
{s:'ps',t:'Binomial PMF',f:'P(X=k)=\\binom{n}{k}p^k(1-p)^{n-k}',n:'E=np, Var=np(1−p)'},{s:'ps',t:'Poisson PMF',f:'P(X=k)=\\dfrac{e^{-\\lambda}\\lambda^k}{k!}',n:'E = Var = λ'},
{s:'ps',t:'Normal PDF',f:'f(x)=\\dfrac{1}{\\sigma\\sqrt{2\\pi}}\\,e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}'},{s:'ps',t:'CLT',f:'\\dfrac{\\bar X-\\mu}{\\sigma/\\sqrt n}\\xrightarrow{\\;d\\;}N(0,1)'},
{s:'ps',t:'Confidence interval',f:'\\bar X\\pm z_{\\alpha/2}\\dfrac{\\sigma}{\\sqrt n}',n:'95% → z=1.96'},{s:'ps',t:'Chi-squared test',f:'\\chi^2=\\sum\\dfrac{(O_i-E_i)^2}{E_i}'},
{s:'la',t:'Rank–nullity',f:'rank(A)+nullity(A)=n'},{s:'la',t:'2×2 determinant',f:'\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}=ad-bc'},
{s:'la',t:'Inverse',f:'A^{-1}=\\dfrac{adj(A)}{\\det A}'},{s:'la',t:'Eigen equation',f:'Av=\\lambda v\\iff\\det(A-\\lambda I)=0'},
{s:'la',t:'Trace & det',f:'\\textstyle\\sum\\lambda_i=tr(A);\\;\\prod\\lambda_i=\\det(A)'},{s:'la',t:'Orthogonal matrix',f:'Q^TQ=I;\\;\\det Q=\\pm1'},
{s:'la',t:'Projection',f:'P=A(A^TA)^{-1}A^T;\\;P^2=P'},{s:'la',t:'SVD',f:'A=U\\Sigma V^T',n:'σᵢ = √λᵢ(AA)'},
{s:'co',t:'Derivative',f:"f'(x)=\\lim_{h\\to0}\\dfrac{f(x+h)-f(x)}{h}"},{s:'co',t:"L'Hôpital",f:"\\lim\\dfrac{f}{g}=\\lim\\dfrac{f'}{g'}",n:'0/0 or ∞/∞ only'},
{s:'co',t:'Taylor',f:'f(x)=\\sum_{n=0}^{\\infty}\\dfrac{f^{(n)}(a)}{n!}(x-a)^n'},{s:'co',t:'Extrema',f:"f'(c)=0;\\;f''(c)<0\\Rightarrow\\max"},
{s:'co',t:'Gradient descent',f:'x_{t+1}=x_t-\\alpha\\nabla f(x_t)'},{s:'pdsa',t:'Search',f:'\\text{linear }O(n);\\;\\text{binary }O(\\log n)'},
{s:'pdsa',t:'Sort table',f:'\\text{merge }O(n\\log n);\\;\\text{quick worst }O(n^2)'},{s:'pdsa',t:'Dijkstra',f:'O((V+E)\\log V)',n:'non-negative weights'},
{s:'dbms',t:'Normal forms',f:'1NF\\to2NF\\to3NF\\to BCNF'},{s:'dbms',t:'SQL order',f:'FROM\\to WHERE\\to GROUP\\;BY\\to HAVING\\to SELECT'},
{s:'ml',t:'OLS',f:'\\hat\\beta=(X^TX)^{-1}X^Ty'},{s:'ml',t:'Ridge',f:'\\hat\\beta=(X^TX+\\lambda I)^{-1}X^Ty'},
{s:'ml',t:'Sigmoid',f:'\\sigma(z)=\\dfrac{1}{1+e^{-z}}'},{s:'ml',t:'Entropy',f:'H=-\\sum p_i\\log_2 p_i'},
{s:'ml',t:'SVM margin',f:'\\dfrac{2}{\\|w\\|}'},{s:'ml',t:'k-means',f:'\\min\\sum_k\\sum_{x\\in C_k}\\|x-\\mu_k\\|^2'},
{s:'ml',t:'PCA variance',f:'\\dfrac{\\lambda_i}{\\sum_j\\lambda_j}'},{s:'ai',t:'A*',f:'f(n)=g(n)+h(n)',n:'optimal if h admissible'},
{s:'ai',t:'α–β pruning',f:'\\text{cut when }\\alpha\\ge\\beta'},{s:'ai',t:'Belief network',f:'P(x_1,\\dots,x_n)=\\prod_i P(x_i\\mid Parents(x_i))'}
];