const SUBJECT_META = {
  ps:   { name:'Probability & Statistics', color:'#e8a23d' },
  la:   { name:'Linear Algebra', color:'#5aa9e6' },
  co:   { name:'Calculus & Optimization', color:'#c792ea' },
  pdsa: { name:'Programming, Data Structures & Algorithms', color:'#35d07f' },
  dbms: { name:'Database Management & Warehousing', color:'#ff8a5c' },
  ml:   { name:'Machine Learning', color:'#ff6b46' },
  ai:   { name:'Artificial Intelligence', color:'#f6c445' },
  rev:  { name:'Full Revision & Mock Tests', color:'#8a8fa0' },
};
const SUBJECT_ORDER = ['ps','la','co','pdsa','dbms','ml','ai','rev'];

const TOPICS = [
  // Probability & Statistics
  {s:'ps', w:1, t:'Counting: permutations and combinations', f:'nPr = \\dfrac{n!}{(n-r)!},\\quad nCr = \\dfrac{n!}{r!(n-r)!}'},
  {s:'ps', w:1, t:'Probability axioms', f:'P(\\Omega)=1,\\ P(A)\\ge 0,\\ P\\left(\\bigcup_i A_i\\right)=\\sum_i P(A_i)'},
  {s:'ps', w:1, t:'Sample space', f:'P(A)=\\dfrac{n(A)}{n(\\Omega)}'},
  {s:'ps', w:1, t:'Events', f:'P(A^c) = 1-P(A)'},
  {s:'ps', w:1, t:'Independent events', f:'P(A\\cap B) = P(A)\\,P(B)'},
  {s:'ps', w:1, t:'Mutually exclusive events', f:'P(A\\cap B)=0 \\Rightarrow P(A\\cup B)=P(A)+P(B)'},
  {s:'ps', w:1, t:'Marginal probability', f:'P(A) = \\sum_j P(A \\cap B_j)'},
  {s:'ps', w:1, t:'Conditional probability', f:'P(A|B) = \\dfrac{P(A\\cap B)}{P(B)}'},
  {s:'ps', w:1, t:'Joint probability', f:'P(A\\cap B) = P(A|B)P(B) = P(B|A)P(A)'},
  {s:'ps', w:1, t:"Bayes' theorem", f:'P(A_i|B) = \\dfrac{P(B|A_i)P(A_i)}{\\sum_j P(B|A_j)P(A_j)}'},
  {s:'ps', w:1, t:'Conditional expectation', f:'E[X|Y{=}y] = \\sum_x x\\,P(X{=}x|Y{=}y)'},
  {s:'ps', w:1, t:'Conditional variance', f:'Var(X) = E[Var(X|Y)] + Var(E[X|Y])'},
  {s:'ps', w:1, t:'Mean', f:'E[X] = \\sum_x x\\,p(x)\\quad \\text{or}\\quad \\int x f(x)\\,dx'},
  {s:'ps', w:2, t:'Median', f:'\\text{value } m:\\ P(X\\le m)\\ge \\tfrac12,\\ P(X\\ge m)\\ge \\tfrac12'},
  {s:'ps', w:2, t:'Mode', f:'\\text{value with max } p(x) \\text{ or } f(x)'},
  {s:'ps', w:2, t:'Standard deviation', f:'\\sigma = \\sqrt{Var(X)},\\quad Var(X)=E[X^2]-(E[X])^2'},
  {s:'ps', w:2, t:'Correlation', f:'\\rho_{XY} = \\dfrac{Cov(X,Y)}{\\sigma_X \\sigma_Y},\\ -1\\le \\rho \\le 1'},
  {s:'ps', w:2, t:'Covariance', f:'Cov(X,Y) = E[XY]-E[X]E[Y]'},
  {s:'ps', w:2, t:'Random variables', f:'X:\\Omega \\to \\mathbb{R}'},
  {s:'ps', w:2, t:'Discrete random variables & probability mass functions', f:'p(x)=P(X{=}x),\\quad \\sum_x p(x)=1'},
  {s:'ps', w:2, t:'Uniform distribution (discrete)', f:'p(x)=\\dfrac1n,\\ E[X]=\\dfrac{n+1}{2}'},
  {s:'ps', w:2, t:'Bernoulli distribution', f:'P(X{=}1)=p,\\ E[X]=p,\\ Var(X)=p(1-p)'},
  {s:'ps', w:2, t:'Binomial distribution', f:'P(X{=}k)=\\binom{n}{k}p^k(1-p)^{n-k},\\ E[X]=np'},
  {s:'ps', w:2, t:'Continuous random variables & probability distribution function', f:'P(a\\le X\\le b)=\\int_a^b f(x)\\,dx,\\ \\int f(x)\\,dx=1'},
  {s:'ps', w:2, t:'Uniform distribution (continuous)', f:'f(x)=\\dfrac{1}{b-a},\\ E[X]=\\dfrac{a+b}{2}'},
  {s:'ps', w:3, t:'Exponential distribution', f:'f(x)=\\lambda e^{-\\lambda x},\\ E[X]=\\dfrac1\\lambda'},
  {s:'ps', w:3, t:'Poisson distribution', f:'P(X{=}k)=\\dfrac{e^{-\\lambda}\\lambda^k}{k!},\\ E[X]=Var(X)=\\lambda'},
  {s:'ps', w:3, t:'Normal distribution', f:'f(x)=\\dfrac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}'},
  {s:'ps', w:3, t:'Standard normal distribution', f:'Z=\\dfrac{X-\\mu}{\\sigma}\\sim N(0,1)'},
  {s:'ps', w:3, t:'t-distribution', f:'T=\\dfrac{Z}{\\sqrt{\\chi^2_\\nu/\\nu}}'},
  {s:'ps', w:3, t:'Chi-squared distribution', f:'\\chi^2=\\sum_{i=1}^{\\nu} Z_i^2'},
  {s:'ps', w:3, t:'Cumulative distribution function (CDF)', f:'F(x)=P(X\\le x)=\\int_{-\\infty}^{x} f(t)\\,dt'},
  {s:'ps', w:3, t:'Conditional PDF', f:'f(x|y)=\\dfrac{f(x,y)}{f_Y(y)}'},
  {s:'ps', w:3, t:'Central limit theorem', f:'\\dfrac{\\bar X-\\mu}{\\sigma/\\sqrt n}\\ \\xrightarrow{d}\\ N(0,1)'},
  {s:'ps', w:3, t:'Confidence interval', f:'\\bar X \\pm z_{\\alpha/2}\\dfrac{\\sigma}{\\sqrt n}'},
  {s:'ps', w:3, t:'z-test', f:'z=\\dfrac{\\bar X-\\mu_0}{\\sigma/\\sqrt n}'},
  {s:'ps', w:3, t:'t-test', f:'t=\\dfrac{\\bar X-\\mu_0}{s/\\sqrt n},\\ df=n-1'},
  {s:'ps', w:3, t:'Chi-squared test', f:'\\chi^2=\\sum \\dfrac{(O_i-E_i)^2}{E_i}'},

  // Linear Algebra
  {s:'la', w:4, t:'Vector space', tip:'A set closed under vector addition and scalar multiplication'},
  {s:'la', w:4, t:'Subspaces', f:'W\\subseteq V:\\ 0\\in W,\\ \\text{closed under }+,\\cdot'},
  {s:'la', w:4, t:'Linear dependence and independence of vectors', f:'c_1v_1+\\dots+c_nv_n=0 \\Rightarrow \\text{all }c_i=0'},
  {s:'la', w:4, t:'Matrices: fundamentals', f:'(AB)^T=B^TA^T,\\quad (AB)^{-1}=B^{-1}A^{-1}'},
  {s:'la', w:4, t:'Projection matrix', f:'P=A(A^TA)^{-1}A^T,\\quad P^2=P=P^T'},
  {s:'la', w:4, t:'Orthogonal matrix', f:'Q^TQ=I,\\quad Q^{-1}=Q^T,\\quad \\det(Q)=\\pm1'},
  {s:'la', w:4, t:'Idempotent matrix', f:'A^2=A'},
  {s:'la', w:4, t:'Partition matrix and its properties', tip:'Block matrices multiply block-by-block'},
  {s:'la', w:4, t:'Quadratic forms', f:'Q(x)=x^TAx;\\ \\text{PD if } x^TAx>0'},
  {s:'la', w:5, t:'Systems of linear equations and their solutions', f:'Ax=b \\text{ consistent} \\iff rank(A)=rank([A|b])'},
  {s:'la', w:5, t:'Gaussian elimination', tip:'Row-reduce [A|b] to echelon form'},
  {s:'la', w:5, t:'Eigenvalues and eigenvectors', f:'Av=\\lambda v \\iff \\det(A-\\lambda I)=0'},
  {s:'la', w:5, t:'Determinant', f:'\\det(AB)=\\det(A)\\det(B)'},
  {s:'la', w:5, t:'Rank', f:'rank(A)=\\dim(\\text{column space of }A)'},
  {s:'la', w:5, t:'Nullity', f:'rank(A)+nullity(A)=n'},
  {s:'la', w:5, t:'Projections', f:'\\text{proj}_u(v)=\\dfrac{u\\cdot v}{u\\cdot u}\\,u'},
  {s:'la', w:5, t:'LU decomposition', f:'A=LU\\ \\text{(}L\\text{ lower, }U\\text{ upper)}'},
  {s:'la', w:5, t:'Singular value decomposition (SVD)', f:'A=U\\Sigma V^T'},

  // Calculus & Optimization
  {s:'co', w:6, t:'Functions of a single variable', f:'f:\\mathbb R \\to \\mathbb R'},
  {s:'co', w:6, t:'Limit', f:'\\lim_{x\\to a} f(x) = L'},
  {s:'co', w:6, t:'Continuity', f:'\\lim_{x\\to a}f(x)=f(a)'},
  {s:'co', w:6, t:'Differentiability', f:"f'(a)=\\lim_{h\\to0}\\dfrac{f(a+h)-f(a)}{h}"},
  {s:'co', w:6, t:'Taylor series', f:'f(x)=\\sum_{n=0}^{\\infty}\\dfrac{f^{(n)}(a)}{n!}(x-a)^n'},
  {s:'co', w:6, t:'Maxima and minima', f:"\\nabla f(x) = 0, \\; \\nabla^2 f(x) \\text{ sign test}"},
  {s:'co', w:6, t:'Optimization involving a single variable', f:"\\arg\\min_{x} f(x) \\text{ s.t. } x \\in S"},

  // PDSA
  {s:'pdsa', w:6, t:'Programming in Python', tip:'Focus on list/dict comprehensions, recursion, and time complexity'},
  {s:'pdsa', w:6, t:'Stacks', f:'\\text{LIFO — push/pop: } \\mathcal O(1)'},
  {s:'pdsa', w:6, t:'Queues', f:'\\text{FIFO — enqueue/dequeue: } \\mathcal O(1)'},
  {s:'pdsa', w:6, t:'Linked lists', f:'\\text{Insert/delete: } \\mathcal O(1),\\quad \\text{Search: } \\mathcal O(n)'},
  {s:'pdsa', w:6, t:'Trees', f:'\\text{Binary tree of height } h: \\le 2^{h+1}-1 \\text{ nodes}'},
  {s:'pdsa', w:6, t:'Hash tables', f:'\\text{Avg access: } \\mathcal O(1);\\quad \\text{load factor } \\alpha = n/m'},
  {s:'pdsa', w:7, t:'Linear search', f:'\\mathcal O(n)'},
  {s:'pdsa', w:7, t:'Binary search', f:'\\mathcal O(\\log n)\\ \\text{— array must be sorted}'},
  {s:'pdsa', w:7, t:'Selection sort', f:'\\mathcal O(n^2)'},
  {s:'pdsa', w:7, t:'Bubble sort', f:'\\mathcal O(n^2)'},
  {s:'pdsa', w:7, t:'Insertion sort', f:'\\mathcal O(n^2),\\ \\mathcal O(n) \\text{ best case}'},
  {s:'pdsa', w:7, t:'Merge sort (divide and conquer)', f:'\\mathcal O(n\\log n),\\ \\text{stable, } \\mathcal O(n) \\text{ extra space}'},
  {s:'pdsa', w:7, t:'Quicksort (divide and conquer)', f:'\\mathcal O(n\\log n) \\text{ avg},\\ \\mathcal O(n^2) \\text{ worst}'},
  {s:'pdsa', w:7, t:'Introduction to graph theory', f:'G=(V,E);\\quad |E|\\le \\dfrac{n(n-1)}{2}'},
  {s:'pdsa', w:7, t:'Graph traversals', f:'\\text{BFS / DFS: } \\mathcal O(V+E)'},
  {s:'pdsa', w:7, t:'Shortest path algorithms', f:'\\text{Dijkstra: } \\mathcal O((V{+}E)\\log V)'},

  // DBMS
  {s:'dbms', w:8, t:'ER-model', tip:'Entities, attributes, relationships — cardinality 1:1, 1:N, M:N'},
  {s:'dbms', w:8, t:'Relational model', tip:'Table = relation, row = tuple, column = attribute'},
  {s:'dbms', w:8, t:'Relational algebra', f:'\\sigma\\ \\text{(select)},\\ \\pi\\ \\text{(project)},\\ \\bowtie\\ \\text{(join)}'},
  {s:'dbms', w:8, t:'Tuple calculus', f:'\\{\\,t \\mid P(t)\\,\\}'},
  {s:'dbms', w:8, t:'SQL', tip:'Logical execution order: FROM → WHERE → GROUP BY → HAVING → SELECT'},
  {s:'dbms', w:8, t:'Integrity constraints', tip:'Primary key, foreign key, NOT NULL, unique, check constraints'},
  {s:'dbms', w:8, t:'Normal forms', tip:'1NF → 2NF → 3NF → BCNF: progressively remove partial & transitive dependencies'},
  {s:'dbms', w:8, t:'File organization', tip:'Sequential, heap (unordered), and hashed file organization'},
  {s:'dbms', w:8, t:'Indexing', f:'\\text{B+ tree height} = \\mathcal O(\\log_f n)'},
  {s:'dbms', w:8, t:'Data types', tip:'INT, CHAR/VARCHAR, DATE, BOOLEAN, FLOAT'},
  {s:'dbms', w:8, t:'Data transformation: normalization', tip:'Rescale values, e.g. min-max or z-score, before modelling'},
  {s:'dbms', w:8, t:'Data transformation: discretization', tip:'Bin continuous values into intervals'},
  {s:'dbms', w:8, t:'Data transformation: sampling', tip:'Simple random, stratified, and systematic sampling'},
  {s:'dbms', w:8, t:'Data transformation: compression', tip:'Reduce storage via lossless or lossy encoding'},
  {s:'dbms', w:8, t:'Data warehouse schema for multidimensional models', tip:'Star schema, snowflake schema'},
  {s:'dbms', w:8, t:'Concept hierarchies', tip:'e.g. day < month < quarter < year'},
  {s:'dbms', w:8, t:'Measures: categorization', tip:'Distributive (SUM), algebraic (AVG), holistic (MEDIAN)'},
  {s:'dbms', w:8, t:'Measures: computations', tip:'Aggregate functions: SUM, COUNT, AVG, MIN, MAX'},

  // Machine Learning
  {s:'ml', w:9, t:'Regression and classification problems', f:'y=f(x)+\\epsilon\\ \\text{(regression)};\\quad y\\in\\{1,\\dots,K\\}\\ \\text{(classification)}'},
  {s:'ml', w:9, t:'Simple linear regression', f:'\\hat\\beta_1=\\dfrac{Cov(X,Y)}{Var(X)},\\quad \\hat\\beta_0=\\bar y-\\hat\\beta_1\\bar x'},
  {s:'ml', w:9, t:'Multiple linear regression', f:'\\hat\\beta=(X^TX)^{-1}X^Ty'},
  {s:'ml', w:9, t:'Ridge regression', f:'\\hat\\beta=(X^TX+\\lambda I)^{-1}X^Ty'},
  {s:'ml', w:9, t:'Logistic regression', f:'p=\\dfrac{1}{1+e^{-(\\beta_0+\\beta_1x)}}'},
  {s:'ml', w:9, t:'k-nearest neighbour', tip:'Classify by majority vote among the k nearest points'},
  {s:'ml', w:9, t:'Naive Bayes classifier', f:'P(y|x)\\propto P(y)\\prod_i P(x_i|y)'},
  {s:'ml', w:9, t:'Linear discriminant analysis', f:'\\max \\dfrac{(\\mu_1-\\mu_2)^2}{\\sigma_1^2+\\sigma_2^2}'},
  {s:'ml', w:9, t:'Support vector machine', f:'\\max \\dfrac{2}{\\|w\\|}\\quad \\text{s.t. } y_i(w\\cdot x_i+b)\\ge1'},
  {s:'ml', w:9, t:'Decision trees', tip:'Split on the feature giving maximum information gain'},
  {s:'ml', w:9, t:'Bias-variance trade-off', f:'E[(y-\\hat y)^2] = Bias^2+Variance+\\sigma^2'},
  {s:'ml', w:10, t:'Leave-one-out (LOO) cross-validation', f:'n \\text{ folds — train on } n{-}1,\\ \\text{test on the } 1'},
  {s:'ml', w:10, t:'k-fold cross-validation', f:'k \\text{ folds — train on } k{-}1,\\ \\text{test on the remaining fold}'},
  {s:'ml', w:10, t:'Multi-layer perceptron', f:'a^{(l)}=\\sigma\\!\\left(W^{(l)}a^{(l-1)}+b^{(l)}\\right)'},
  {s:'ml', w:10, t:'Feed-forward neural network', f:'\\hat y = \\sigma(W_2\\,\\sigma(W_1x+b_1)+b_2)'},
  {s:'ml', w:10, t:'Clustering algorithms (overview)', tip:'Group unlabelled data by similarity'},
  {s:'ml', w:10, t:'k-means clustering', f:'\\min \\sum_k\\sum_{x\\in C_k}\\|x-\\mu_k\\|^2'},
  {s:'ml', w:10, t:'k-medoid clustering', tip:'Like k-means, but each cluster centre is an actual data point'},
  {s:'ml', w:10, t:'Hierarchical clustering: divisive (top-down)', tip:'Start with one cluster and recursively split it'},
  {s:'ml', w:10, t:'Hierarchical clustering: agglomerative, single-linkage', f:'d(A,B)=\\min_{a\\in A,\\,b\\in B}\\|a-b\\|'},
  {s:'ml', w:10, t:'Hierarchical clustering: complete/multiple-linkage', f:'d(A,B)=\\max_{a\\in A,\\,b\\in B}\\|a-b\\|'},
  {s:'ml', w:10, t:'Dimensionality reduction', tip:'Reduce feature count while preserving information'},
  {s:'ml', w:10, t:'Principal component analysis (PCA)', tip:'Eigenvectors of the covariance matrix, sorted by eigenvalue'},

  // AI
  {s:'ai', w:11, t:'Search: uninformed', tip:'BFS, DFS, uniform-cost search — no heuristic used'},
  {s:'ai', w:11, t:'Search: informed', f:'f(n)=g(n)+h(n)\\ \\text{(A* search)}'},
  {s:'ai', w:11, t:'Search: adversarial', tip:'Minimax search, with alpha-beta pruning'},
  {s:'ai', w:11, t:'Logic: propositional', f:'\\wedge,\\ \\vee,\\ \\neg,\\ \\rightarrow,\\ \\leftrightarrow'},
  {s:'ai', w:11, t:'Logic: predicate', f:'\\forall x\\,P(x),\\quad \\exists x\\,P(x)'},
  {s:'ai', w:11, t:'Reasoning under uncertainty: conditional independence', f:'P(X,Y|Z)=P(X|Z)\\,P(Y|Z)'},
  {s:'ai', w:11, t:'Exact inference: variable elimination', tip:'Sum out variables one at a time via factor marginalization'},
  {s:'ai', w:11, t:'Approximate inference: sampling', tip:'Monte Carlo methods — likelihood weighting, Gibbs sampling'},

  // Revision
  {s:'rev', w:12, t:'Full revision — Probability, Linear Algebra, Calculus', tip:'Redo your formula sheet; work 10 mixed problems per topic'},
  {s:'rev', w:12, t:'Full revision — PDSA, DBMS, ML, AI', tip:'Redo your formula sheet; work 10 mixed problems per topic'},
  {s:'rev', w:12, t:'Previous year GATE DA paper — attempt 1', tip:'Simulate full 3-hour test conditions, no notes'},
  {s:'rev', w:12, t:'Previous year GATE DA paper — attempt 2', tip:'Simulate full 3-hour test conditions, no notes'},
  {s:'rev', w:12, t:'Full-length mock test 1', tip:'Analyze section-wise accuracy and timing right after'},
  {s:'rev', w:12, t:'Full-length mock test 2', tip:'Analyze section-wise accuracy and timing right after'},
  {s:'rev', w:12, t:'Rework mistakes from mocks & weak topics', tip:'Keep a running error log — revisit it the night before the exam'},
  {s:'rev', w:12, t:'Final formula & concept sheet pass', tip:'One page per subject — glance through on exam morning only'},
];
TOPICS.forEach((topic, i) => topic.id = 's' + i);

const MATH_DATABASE = {
  "counting: permutations and combinations": {
    def: "Rigorous combinatorics managing constraints, partitions, and allocations over discrete sets using mappings.",
    thm: "<h5>Stars and Bars Theorem (Theorem II)</h5><p>The number of distinct non-negative integer solutions to $\\sum_{i=1}^k x_i = n$ is given exactly by $\\binom{n+k-1}{k-1}$.</p>",
    ctr: "<span class=\"counter-title\">Distinct vs Indistinct Objects</span>Conflating Stirling numbers of the second kind (allocating distinct objects to indistinct buckets) with standard combinations.",
    ex: "<p><strong>Problem:</strong> A network router has 5 distinct outbound processing queues. It receives 12 identical packets that must be allocated concurrently. Find the exact probability that no processing queue remains completely idle.</p><p><strong>Solution:</strong> This maps to finding the positive integer solutions to $x_1 + x_2 + x_3 + x_4 + x_5 = 12$. By applying Stars and Bars (Theorem I), total allocations without constraints is $\\binom{12+5-1}{5-1} = \\binom{16}{4} = 1820$. The number of positive integer solutions (no queue empty) is $\\binom{12-1}{5-1} = \\binom{11}{4} = 330$. Hence, the exact mathematical probability is $\\frac{330}{1820} = \\frac{33}{182}$.</p>"
  },
  "poisson distribution": {
    def: "A limiting form of the Binomial distribution where the number of trials $n \\to \\infty$ and $p \\to 0$ such that $np = \\lambda$.",
    thm: "<h5>Additive Property of Independent Poisson Variables</h5><p>If $X_1 \\sim \\text{Poi}(\\lambda_1)$ and $X_2 \\sim \\text{Poi}(\\lambda_2)$ are independent, then $X_1 + X_2 \\sim \\text{Poi}(\\lambda_1 + \\lambda_2)$.</p>",
    ctr: "<span class=\"counter-title\">Time Dependence & Clumping</span>Using a constant rate parameter $\\lambda$ when events display temporal clustering, which violates the memoryless independent increments axiom.",
    ex: "<p><strong>Problem:</strong> A distributed cloud server encounters runtime faults at a mean rate of 3 errors per hour, matching a Poisson process. Calculate the exact conditional probability that exactly 2 faults occurred in the first 20 minutes, given that 5 faults occurred in the first hour.</p><p><strong>Solution:</strong> Let $X$ be faults in the first 20 mins ($t_1=1/3$ hour), so $X \\sim \\text{Poi}(\\lambda_1 = 3 \\times 1/3 = 1)$. Let $Y$ be faults in the remaining 40 mins, so $Y \\sim \\text{Poi}(\\lambda_2 = 2)$. We want $P(X=2 | X+Y=5) = \\frac{P(X=2)P(Y=3)}{P(X+Y=5)}$. Utilizing the distributions: $\\frac{(e^{-1}\\frac{1^2}{2!}) \\cdot (e^{-2}\\frac{2^3}{3!})}{e^{-3}\\frac{3^5}{5!}} = \\frac{\\frac{1}{2} \\cdot \\frac{8}{6}}{\\frac{243}{120}} = \\frac{8}{6} \\cdot \\frac{60}{243} = \\frac{80}{243}$.</p>"
  },
  "projection matrix": {
    def: "An operator mapping a vector space orthogonally onto a lower-dimensional subspace without scaling alterations. $$P = A(A^TA)^{-1}A^T$$",
    thm: "<h5>Idempotency and Eigenvalues</h5><p>For any valid projection matrix, $P^2 = P = P^T$, and its unique eigenvalues must satisfy $\\lambda \\in \\{0, 1\\}$.</p>",
    ctr: "<span class=\"counter-title\">Non-orthogonal Projections</span>Assuming $P = AA^T$ projects correctly onto a subspace when column vectors of $A$ are not mutually orthogonal.",
    ex: "<p><strong>Problem:</strong> Construct the precise $3 \\times 3$ projection matrix $P$ that maps any vector in $\\mathbb{R}^3$ onto the plane spanned by the column vectors $v_1 = [1, 1, 0]^T$ and $v_2 = [0, 1, 1]^T$.</p><p><strong>Solution:</strong> Build matrix $A = \\begin{pmatrix} 1 & 0 \\\\ 1 & 1 \\\\ 0 & 1 \\end{pmatrix}$. Compute $A^TA = \\begin{pmatrix} 2 & 1 \\\\ 1 & 2 \\end{pmatrix}$. The matrix inverse is $(A^TA)^{-1} = \\frac{1}{3}\\begin{pmatrix} 2 & -1 \\\\ -1 & 2 \\end{pmatrix}$. Compute $A(A^TA)^{-1} = \\frac{1}{3}\\begin{pmatrix} 2 & -1 \\\\ 1 & 1 \\\\ -1 & 2 \\end{pmatrix}$. Finally, $P = A(A^TA)^{-1}A^T = \\frac{1}{3}\\begin{pmatrix} 2 & 1 & -1 \\\\ 1 & 2 & 1 \\\\ -1 & 1 & 2 \\end{pmatrix}$.</p>"
  },
  "singular value decomposition (svd)": {
    def: "Factorization of any real matrix into orthogonal spaces and geometric singular extensions: $$A = U \\Sigma V^T$$",
    thm: "<h5>Eckart-Young-Mirsky Theorem</h5><p>The optimal rank-$k$ approximation of a matrix under the Frobenius norm is constructed by setting all but the $k$-largest singular values to 0.</p>",
    ctr: "<span class=\"counter-title\">Singular Value vs Eigenvalue</span>Conflating the singular values of $A$ with eigenvalues of $A$. Singular values are always non-negative square roots of eigenvalues of $A^TA$.",
    ex: "<p><strong>Problem:</strong> Find the exact Singular Value Decomposition (SVD) of the matrix $A = \\begin{pmatrix} 3 & 0 \\\\ 0 & -2 \\end{pmatrix}$.</p><p><strong>Solution:</strong> We compute $A^TA = \\begin{pmatrix} 9 & 0 \\\\ 0 & 4 \\end{pmatrix}$. The eigenvalues are $\\lambda_1=9, \\lambda_2=4$, which yields singular values $\\sigma_1=3, \\sigma_2=2$. The right singular vectors (eigenvectors of $A^TA$) are $v_1=[1,0]^T, v_2=[0,1]^T$, meaning $V=I$. The left singular vectors are given by $u_i = \\frac{1}{\\sigma_i}Av_i$. Thus $u_1 = \\frac{1}{3}[3,0]^T = [1,0]^T$ and $u_2 = \\frac{1}{2}[0,-2]^T = [0,-1]^T$. Hence, $A = \\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix} \\begin{pmatrix} 3 & 0 \\\\ 0 & 2 \\end{pmatrix} \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}^T$.</p>"
  }
};
