const FORMULAS=[
{s:'ps',t:'Permutations',f:'P(n,r)=\\dfrac{n!}{(n-r)!}'},
{s:'ps',t:'Combinations',f:'C(n,r)=\\dfrac{n!}{r!(n-r)!}'},
{s:'ps',t:'Addition rule',f:'P(A\\cup B)=P(A)+P(B)-P(A\\cap B)',n:'Disjoint → P(A∩B)=0'},
{s:'ps',t:'Complement',f:'P(A^c)=1-P(A)'},
{s:'ps',t:'Conditional probability',f:'P(A|B)=\\dfrac{P(A\\cap B)}{P(B)}'},
{s:'ps',t:'Independence',f:'P(A\\cap B)=P(A)\\,P(B)'},
{s:'ps',t:'Law of total probability',f:'P(B)=\\sum_i P(B|A_i)P(A_i)'},
{s:'ps',t:"Bayes' theorem",f:'P(A_i|B)=\\dfrac{P(B|A_i)P(A_i)}{\\sum_j P(B|A_j)P(A_j)}'},
{s:'ps',t:'Expectation',f:'E[X]=\\sum_x x\\,p(x)\\;\\text{or}\\;\\int x\\,f(x)\\,dx'},
{s:'ps',t:'Variance',f:'Var(X)=E[X^2]-(E[X])^2'},
{s:'ps',t:'Law of total variance',f:'Var(X)=E[Var(X|Y)]+Var(E[X|Y])'},
{s:'ps',t:'Covariance',f:'Cov(X,Y)=E[XY]-E[X]E[Y]'},
{s:'ps',t:'Correlation',f:'\\rho=\\dfrac{Cov(X,Y)}{\\sigma_X\\sigma_Y}\\in[-1,1]'},
{s:'ps',t:'Bernoulli',f:'E=p,\\quad Var=p(1-p)'},
{s:'ps',t:'Binomial PMF',f:'P(X=k)=\\binom{n}{k}p^k(1-p)^{n-k}',n:'E=np, Var=np(1−p)'},
{s:'ps',t:'Poisson PMF',f:'P(X=k)=\\dfrac{e^{-\\lambda}\\lambda^k}{k!}',n:'E = Var = λ'},
{s:'ps',t:'Uniform (continuous)',f:'f(x)=\\dfrac{1}{b-a},\\;E=\\dfrac{a+b}{2},\\;Var=\\dfrac{(b-a)^2}{12}'},
{s:'ps',t:'Exponential',f:'f(x)=\\lambda e^{-\\lambda x},\\;E=\\dfrac1\\lambda',n:'Memoryless'},
{s:'ps',t:'Normal PDF',f:'f(x)=\\dfrac{1}{\\sigma\\sqrt{2\\pi}}\\,e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}'},
{s:'ps',t:'Standardization',f:'Z=\\dfrac{X-\\mu}{\\sigma}\\sim N(0,1)',n:'68–95–99.7 rule'},
{s:'ps',t:'CDF ↔ PDF',f:'F(x)=\\int_{-\\infty}^{x}f(t)\\,dt,\\quad f=F\''},
{s:'ps',t:'Central Limit Theorem',f:'\\dfrac{\\bar X-\\mu}{\\sigma/\\sqrt n}\\xrightarrow{\\;d\\;}N(0,1)'},
{s:'ps',t:'Confidence interval',f:'\\bar X\\pm z_{\\alpha/2}\\dfrac{\\sigma}{\\sqrt n}',n:'95% → z=1.96'},
{s:'ps',t:'z statistic',f:'z=\\dfrac{\\bar X-\\mu_0}{\\sigma/\\sqrt n}'},
{s:'ps',t:'t statistic',f:'t=\\dfrac{\\bar X-\\mu_0}{s/\\sqrt n},\\;df=n-1'},
{s:'ps',t:'Chi-squared test',f:'\\chi^2=\\sum\\dfrac{(O_i-E_i)^2}{E_i},\\;df=(r-1)(c-1)'},
{s:'la',t:'Linear independence',f:'\\textstyle\\sum c_iv_i=0\\Rightarrow\\text{all }c_i=0'},
{s:'la',t:'Rank–nullity',f:'rank(A)+nullity(A)=n'},
{s:'la',t:'System consistency',f:'Ax=b\\text{ solvable}\\iff rank(A)=rank([A|b])'},
{s:'la',t:'2×2 determinant',f:'\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}=ad-bc'},
{s:'la',t:'Determinant rules',f:'\\det(AB)=\\det A\\,\\det B;\\;\\det(kA)=k^n\\det A'},
{s:'la',t:'Inverse',f:'A^{-1}=\\dfrac{adj(A)}{\\det A};\\;(AB)^{-1}=B^{-1}A^{-1}'},
{s:'la',t:'Eigen equation',f:'Av=\\lambda v\\iff\\det(A-\\lambda I)=0'},
{s:'la',t:'Trace & det from eigenvalues',f:'\\textstyle\\sum\\lambda_i=tr(A);\\;\\prod\\lambda_i=\\det(A)'},
{s:'la',t:'Orthogonal matrix',f:'Q^TQ=I;\\;\\det Q=\\pm1'},
{s:'la',t:'Projection matrix',f:'P=A(A^TA)^{-1}A^T;\\;P^2=P=P^T'},
{s:'la',t:'Idempotent',f:'A^2=A\\;\\Rightarrow\\;\\lambda\\in\\{0,1\\}'},
{s:'la',t:'Quadratic form',f:'q(x)=x^TAx\\text{ PD}\\iff\\lambda_i>0'},
{s:'la',t:'LU decomposition',f:'A=LU'},
{s:'la',t:'SVD',f:'A=U\\Sigma V^T;\\;\\sigma_i=\\sqrt{\\lambda_i(A^TA)}',n:'Best rank-k approx: keep top-k σ'},
{s:'la',t:"Cramer's rule",f:'x_i=\\dfrac{\\det(A_i)}{\\det(A)}'},
{s:'co',t:'Limit (ε–δ)',f:'\\forall\\epsilon>0,\\exists\\delta>0:|x-a|<\\delta\\Rightarrow|f(x)-L|<\\epsilon'},
{s:'co',t:'Derivative definition',f:"f'(x)=\\lim_{h\\to0}\\dfrac{f(x+h)-f(x)}{h}"},
{s:'co',t:'Product rule',f:"(fg)'=f'g+fg'"},
{s:'co',t:'Quotient rule',f:"\\left(\\dfrac{f}{g}\\right)'=\\dfrac{f'g-fg'}{g^2}"},
{s:'co',t:'Chain rule',f:"(f\\circ g)'(x)=f'(g(x))\\,g'(x)"},
{s:'co',t:"L'Hôpital's rule",f:"\\lim\\dfrac{f}{g}=\\lim\\dfrac{f'}{g'}",n:'Only 0/0 or ∞/∞'},
{s:'co',t:'Classic limit',f:'\\lim_{x\\to\\infty}\\left(1+\\dfrac1x\\right)^x=e'},
{s:'co',t:'Taylor series',f:'f(x)=\\sum_{n=0}^{\\infty}\\dfrac{f^{(n)}(a)}{n!}(x-a)^n'},
{s:'co',t:'Extrema tests',f:"f'(c)=0;\\;f''(c)<0\\Rightarrow\\max;\\;f''(c)>0\\Rightarrow\\min"},
{s:'co',t:'Gradient descent',f:'x_{t+1}=x_t-\\alpha\\nabla f(x_t)'},
{s:'co',t:"Newton's method",f:'x_{t+1}=x_t-[H(x_t)]^{-1}\\nabla f(x_t)'},
{s:'co',t:'Lagrange multipliers',f:'\\nabla f=\\lambda\\nabla g'},
{s:'pdsa',t:'Search complexities',f:'\\text{linear }O(n);\\;\\text{binary }O(\\log n)\\text{ [sorted]}'},
{s:'pdsa',t:'Sort table',f:'\\text{sel/bub/ins }O(n^2);\\;\\text{merge }O(n\\log n);\\;\\text{quick worst }O(n^2)'},
{s:'pdsa',t:'Stable sorts',f:'\\text{bubble, insertion, mergesort}',n:'Quick/selection/heap unstable'},
{s:'pdsa',t:'Stack / queue ops',f:'push/pop/enqueue/dequeue\\to O(1)'},
{s:'pdsa',t:'Hash table',f:'avg\\;O(1);\\;\\text{load factor }\\lambda=n/m'},
{s:'pdsa',t:'BST',f:'avg\\;O(\\log n),\\;worst\\;O(n)',n:'In-order traversal = sorted'},
{s:'pdsa',t:'Graph representations',f:'\\text{matrix }O(V^2);\\;\\text{adjacency list }O(V+E)'},
{s:'pdsa',t:'Traversals',f:'BFS\\;(queue),\\;DFS\\;(stack)\\to O(V+E)'},
{s:'pdsa',t:'Dijkstra',f:'O((V+E)\\log V)',n:'Non-negative weights only'},
{s:'pdsa',t:'Master theorem',f:'T(n)=aT(n/b)+\\Theta(n^d)'},
{s:'dbms',t:'Relational algebra',f:'\\sigma,\\;\\pi,\\;\\bowtie,\\;\\cup,\\;\\cap,\\;-\\;,\\;\\rho'},
{s:'dbms',t:'Tuple calculus',f:'\\{\\,t\\mid P(t)\\,\\}'},
{s:'dbms',t:'Integrity constraints',f:'PK\\neq NULL;\\;FK\\in PK_{ref}\\text{ or }NULL'},
{s:'dbms',t:'Armstrong transitivity',f:'X\\to Y,\\;Y\\to Z\\;\\Rightarrow\\;X\\to Z'},
{s:'dbms',t:'Normal forms ladder',f:'1NF\\to2NF\\to3NF\\to BCNF',n:'atomic → no partial → no transitive → determinant = superkey'},
{s:'dbms',t:'SQL evaluation order',f:'FROM\\to WHERE\\to GROUP\\;BY\\to HAVING\\to SELECT\\to ORDER\\;BY'},
{s:'dbms',t:'Star schema',f:'\\text{Fact(measures+FKs)}\\bowtie\\text{denormalized dims}'},
{s:'dbms',t:'Indexing',f:'B^+\\text{-tree }O(\\log n);\\;\\text{hash }O(1)'},
{s:'dbms',t:'ACID',f:'\\text{Atomicity, Consistency, Isolation, Durability}'},
{s:'ml',t:'Simple linear regression',f:'\\hat\\beta_1=\\dfrac{\\sum(x_i-\\bar x)(y_i-\\bar y)}{\\sum(x_i-\\bar x)^2};\\;\\hat\\beta_0=\\bar y-\\hat\\beta_1\\bar x'},
{s:'ml',t:'Normal equation',f:'\\hat\\beta=(X^TX)^{-1}X^Ty'},
{s:'ml',t:'Ridge (L2)',f:'\\hat\\beta=(X^TX+\\lambda I)^{-1}X^Ty'},
{s:'ml',t:'Lasso (L1)',f:'\\min\\;RSS+\\lambda\\|\\beta\\|_1',n:'Sparse → feature selection'},
{s:'ml',t:'R²',f:'R^2=1-\\dfrac{RSS}{TSS}'},
{s:'ml',t:'Sigmoid',f:'\\sigma(z)=\\dfrac{1}{1+e^{-z}}'},
{s:'ml',t:'Logistic model',f:'P(y=1|x)=\\sigma(w^Tx)'},
{s:'ml',t:'Log-likelihood',f:'\\ell=\\sum y_i\\log\\hat p_i+(1-y_i)\\log(1-\\hat p_i)'},
{s:'ml',t:'k-NN distance',f:'d(x,z)=\\sqrt{\\textstyle\\sum_j(x_j-z_j)^2}'},
{s:'ml',t:'Naive Bayes',f:'P(y|x)\\propto P(y)\\prod_i P(x_i|y)'},
{s:'ml',t:'LDA',f:'\\max\\dfrac{w^TS_Bw}{w^TS_Ww}'},
{s:'ml',t:'SVM',f:'\\min\\tfrac12\\|w\\|^2\\;s.t.\\;y_i(w^Tx_i+b)\\ge1;\\;margin=\\dfrac2{\\|w\\|}'},
{s:'ml',t:'Entropy',f:'H=-\\sum p_i\\log_2 p_i'},
{s:'ml',t:'Gini impurity',f:'G=1-\\sum p_i^2'},
{s:'ml',t:'Information gain',f:'Gain=H_{parent}-\\sum\\dfrac{|S_v|}{|S|}H(S_v)'},
{s:'ml',t:'Bias–variance',f:'E[(y-\\hat y)^2]=Bias^2+Variance+\\sigma^2'},
{s:'ml',t:'MLP layer',f:'a^{(l)}=g\\!\\left(W^{(l)}a^{(l-1)}+b^{(l)}\\right)'},
{s:'ml',t:'Gradient descent update',f:'\\theta\\leftarrow\\theta-\\alpha\\nabla J(\\theta)'},
{s:'ml',t:'k-means objective',f:'\\min\\sum_k\\sum_{x\\in C_k}\\|x-\\mu_k\\|^2'},
{s:'ml',t:'Linkage',f:'\\text{single}=\\min d;\\;\\text{complete}=\\max d'},
{s:'ml',t:'PCA explained variance',f:'\\dfrac{\\lambda_i}{\\sum_j\\lambda_j}'},
{s:'ai',t:'A* evaluation',f:'f(n)=g(n)+h(n)',n:'Optimal if h admissible'},
{s:'ai',t:'Admissibility',f:'h(n)\\le h^*(n)'},
{s:'ai',t:'Minimax complexity',f:'O(b^m)',n:'α–β best case O(b^{m/2})'},
{s:'ai',t:'α–β pruning',f:'\\text{cut when }\\alpha\\ge\\beta'},
{s:'ai',t:'Propositional connectives',f:'\\wedge,\\;\\vee,\\;\\neg,\\;\\Rightarrow,\\;\\Leftrightarrow'},
{s:'ai',t:'Modus ponens',f:'A,\\;A\\Rightarrow B\\;\\vdash\\;B'},
{s:'ai',t:'Resolution',f:'(A\\vee B)\\wedge(\\neg B\\vee C)\\;\\vdash\\;(A\\vee C)'},
{s:'ai',t:'Predicate quantifiers',f:'\\forall x\\,P(x);\\;\\exists x\\,P(x)'},
{s:'ai',t:'Conditional independence',f:'P(X,Y|Z)=P(X|Z)\\,P(Y|Z)'},
{s:'ai',t:'Belief network factorization',f:'P(x_1,\\dots,x_n)=\\prod_i P(x_i\\mid Parents(x_i))'},
{s:'ai',t:'Variable elimination',f:'\\text{sum out hidden vars, reuse factors}',n:'Cost exponential in induced width'},
{s:'ai',t:'Rejection sampling',f:'\\hat P(x|e)=\\dfrac{N(x,e)}{N(e)}'}
];
